
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml

logging:
  level:
    '[io.javabrains]': debug

bucket4j:
  enabled: true
  filters:
  - cache-name: buckets
    url: .*
    rate-limits:
    - bandwidths:
      - capacity: 5
        time: 10
        unit: seconds
